import Foundation

struct FocusSession: Codable {
    enum Phase: String, Codable { case focus, rest }
    var phase: Phase = .focus
    var duration: TimeInterval = 25 * 60
    var deadline: Date?
    var pausedRemaining: TimeInterval = 25 * 60
    var hasStarted = false

    func remaining(at now: Date = Date()) -> TimeInterval {
        max(0, deadline.map { $0.timeIntervalSince(now) } ?? pausedRemaining)
    }
    var running: Bool { deadline != nil }
    func progress(at now: Date = Date()) -> Double {
        min(1, max(0, 1 - remaining(at: now) / max(1, duration)))
    }
    mutating func start(at now: Date = Date()) {
        guard deadline == nil else { return }
        if pausedRemaining <= 0 { pausedRemaining = duration }
        deadline = now.addingTimeInterval(pausedRemaining)
        hasStarted = true
    }
    mutating func pause(at now: Date = Date()) {
        pausedRemaining = remaining(at: now)
        deadline = nil
    }
    mutating func reset(minutes: Int, phase: Phase = .focus) {
        self.phase = phase
        duration = TimeInterval(minutes * 60)
        pausedRemaining = duration
        deadline = nil
        hasStarted = false
    }
    mutating func finishIfNeeded(at now: Date = Date()) -> Bool {
        guard let deadline, deadline <= now else { return false }
        self.deadline = nil
        pausedRemaining = 0
        return true
    }
}

struct ShelfItem: Identifiable, Codable {
    var id: UUID = UUID()
    var path: String
    var bookmark: Data?
    var added = Date()
    var url: URL {
        if let bookmark {
            var stale = false
            if let resolved = try? URL(resolvingBookmarkData: bookmark, options: [.withoutUI, .withoutMounting], relativeTo: nil, bookmarkDataIsStale: &stale) { return resolved }
        }
        return URL(fileURLWithPath: path)
    }
    init(url: URL) {
        path = url.standardizedFileURL.path
        bookmark = try? url.bookmarkData(options: [], includingResourceValuesForKeys: nil, relativeTo: nil)
    }
}

struct ClipEntry: Identifiable, Codable {
    enum Kind: String, Codable { case text, image }
    var id = UUID()
    var kind: Kind
    var text: String?
    var imageData: Data?
    var date = Date()
    var pinned = false
    var byteSize: Int { (text?.utf8.count ?? 0) + (imageData?.count ?? 0) }
    var title: String {
        kind == .image ? "Kopyalanan görsel" : (text ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
    }
}

enum ClipRules {
    static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword",
        "com.typeit4me.clipping", "de.petermaurer.TransientPasteboardType"
    ]
    static func shouldCapture(types: Set<String>) -> Bool { types.isDisjoint(with: excludedTypes) }
    static func trimmed(_ entries: [ClipEntry]) -> [ClipEntry] {
        var bytes = 0
        return entries.sorted {
            if $0.pinned != $1.pinned { return $0.pinned }
            return $0.date > $1.date
        }.prefix(60).filter { item in
            bytes += item.byteSize
            return bytes <= 24 * 1024 * 1024
        }
    }
}

enum DiskStore {
    static var directory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let url = base.appendingPathComponent("Damla", isDirectory: true)
        try? FileManager.default.createDirectory(at: url, withIntermediateDirectories: true,
                                                attributes: [.posixPermissions: 0o700])
        return url
    }
    static func load<T: Decodable>(_ type: T.Type, name: String) -> T? {
        guard let data = try? Data(contentsOf: directory.appendingPathComponent(name)) else { return nil }
        return try? JSONDecoder().decode(type, from: data)
    }
    static func save<T: Encodable>(_ value: T, name: String) {
        guard let data = try? JSONEncoder().encode(value) else { return }
        let url = directory.appendingPathComponent(name)
        do {
            try data.write(to: url, options: .atomic)
            try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
        } catch { NSLog("Damla: local save failed: %@", error.localizedDescription) }
    }
}
