import Foundation

func runSelfTests() -> Int32 {
    var failures: [String] = []
    var count = 0
    func check(_ condition: @autoclosure () -> Bool, _ name: String) {
        count += 1
        if !condition() { failures.append(name) }
    }
    let origin = Date(timeIntervalSince1970: 1_000_000)
    var focus = FocusSession()
    focus.start(at: origin)
    check(focus.remaining(at: origin.addingTimeInterval(60)) == 1440, "Timer tracks elapsed time")
    focus.pause(at: origin.addingTimeInterval(60))
    check(focus.remaining(at: origin.addingTimeInterval(600)) == 1440, "Paused timer does not drift")
    focus.start(at: origin.addingTimeInterval(600))
    check(focus.remaining(at: origin.addingTimeInterval(660)) == 1380, "Resume keeps remaining time")
    let saved = try! JSONEncoder().encode(focus)
    var restored = try! JSONDecoder().decode(FocusSession.self, from: saved)
    check(restored.remaining(at: origin.addingTimeInterval(720)) == 1320, "Restored timer follows wall clock")
    check(restored.finishIfNeeded(at: origin.addingTimeInterval(3000)), "Overdue session completes after wake")
    check(!restored.finishIfNeeded(at: origin.addingTimeInterval(3001)), "Completion counted only once")
    check(restored.remaining(at: origin.addingTimeInterval(3001)) == 0, "Remaining never negative")
    focus.reset(minutes: 5, phase: .rest)
    check(focus.duration == 300 && !focus.running && focus.phase == .rest, "Break resets state")
    check(!ClipRules.shouldCapture(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]), "Password marker excluded")
    check(!ClipRules.shouldCapture(types: ["org.nspasteboard.TransientType"]), "Transient data excluded")
    check(!ClipRules.shouldCapture(types: ["org.nspasteboard.AutoGeneratedType"]), "Own copies excluded")
    check(ClipRules.shouldCapture(types: ["public.png"]), "Images accepted")
    var entries = (0..<70).map { ClipEntry(kind: .text, text: "Test \($0)", date: origin.addingTimeInterval(Double($0))) }
    entries[0].pinned = true
    let trimmed = ClipRules.trimmed(entries)
    check(trimmed.count == 60, "Clipboard bounded to 60")
    check(trimmed.first?.pinned == true, "Pinned entry retained ahead of recents")
    let images = (0..<8).map { _ in ClipEntry(kind: .image, imageData: Data(count: 4 * 1024 * 1024)) }
    check(ClipRules.trimmed(images).reduce(0) { $0 + $1.byteSize } <= 24 * 1024 * 1024, "Clipboard disk budget bounded")
    let temp = FileManager.default.temporaryDirectory.appendingPathComponent("Damla-test-\(UUID().uuidString)")
    do {
        try FileManager.default.createDirectory(at: temp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: temp) }
        let file = temp.appendingPathComponent("original.txt")
        try Data("original stays".utf8).write(to: file)
        let ref = ShelfItem(url: file)
        let roundtrip = try JSONDecoder().decode(ShelfItem.self, from: JSONEncoder().encode(ref))
        check(roundtrip.url.standardizedFileURL.path == file.standardizedFileURL.path, "Shelf reference survives save/reload")
        let original = try String(contentsOf: file, encoding: .utf8)
        check(original == "original stays", "Shelf leaves source unchanged")
    } catch { failures.append("Shelf fixture: \(error)") }
    let notch = Layout.Metrics(notchWidth: 185, notchHeight: 32, hasNotch: true)
    let flat = Layout.Metrics(notchWidth: 0, notchHeight: 30, hasNotch: false)
    check(Layout.shapeSize(.closed, notch, compactContent: false).width == 185 + 12, "Idle notch hugs the physical notch")
    check(Layout.shapeSize(.hud, notch, compactContent: false).width > Layout.shapeSize(.closed, notch, compactContent: true).width, "HUD widens beyond compact content")
    check(Layout.shapeSize(.expanded, notch, compactContent: false).height == 32 + Layout.contentHeight, "Expanded panel sits under the notch")
    check(Layout.shapeSize(.expanded, flat, compactContent: false).height == 12 + Layout.contentHeight, "Notchless panel uses a slim header")
    let window = Layout.windowSize(notch)
    let visible = Layout.visibleRect(.expanded, notch, compactContent: true, midX: 0, top: 0)
    check(window.width >= visible.width && window.height >= visible.height, "Window always contains the drawn shape")
    var cleaning = CleaningSession()
    cleaning.start(at: 100)
    check(cleaning.remaining(at: 159) == 1 && !cleaning.shouldUnlock(at: 159), "Cleaning lock lasts at most 60 seconds")
    check(cleaning.shouldUnlock(at: 160), "Cleaning lock expires without a keyboard event")
    cleaning.start(at: 100, duration: 999)
    check(cleaning.shouldUnlock(at: 160), "Cleaning cannot exceed hard timeout")
    cleaning.escape(down: true, at: 110)
    cleaning.escape(down: true, at: 111.5)
    check(!cleaning.shouldUnlock(at: 111.9) && cleaning.shouldUnlock(at: 112), "Held Esc unlocks after two seconds; repeat does not reset it")
    cleaning.escape(down: false, at: 111)
    check(!cleaning.shouldUnlock(at: 112), "Brief Esc press does not accidentally unlock")
    cleaning.stop()
    check(cleaning.shouldUnlock(at: 101) && cleaning.remaining(at: 101) == 0, "Stopping cleaning clears every deadline")

    var agent = AgentSession(id: "test", provider: .codex, project: "Damla", updated: origin)
    _ = agent.apply(["hook_event_name": "UserPromptSubmit"], at: origin)
    check(agent.phase == .working, "Agent begins from prompt event")
    _ = agent.apply(["hook_event_name": "PermissionRequest", "tool_use_id": "one", "tool_name": "Bash"], at: origin)
    _ = agent.apply(["hook_event_name": "PreToolUse", "tool_use_id": "two", "tool_name": "Bash"], at: origin)
    _ = agent.apply(["hook_event_name": "PostToolUse", "tool_use_id": "two", "tool_name": "Bash"], at: origin)
    check(agent.phase == .waiting && agent.pending.contains("one"), "Parallel tool does not erase outstanding approval")
    _ = agent.apply(["hook_event_name": "PostToolUse", "tool_use_id": "one", "tool_name": "Bash"], at: origin)
    check(agent.phase == .working && agent.pending.isEmpty, "Matching tool completion clears approval")
    check(!agent.apply(["hook_event_name": "Notification", "notification_type": "idle_prompt"], at: origin), "Claude idle nudge is not shown as approval")
    _ = agent.apply(["hook_event_name": "Stop"], at: origin)
    check(agent.phase == .done, "Stop means response completed")
    check(!agent.visibleInNotch(at: origin.addingTimeInterval(61)), "Completed badge expires")
    _ = agent.apply(["hook_event_name": "UserPromptSubmit"], at: origin)
    check(agent.effectivePhase(at: origin.addingTimeInterval(1801)) == .stale, "Missing hook heartbeat is not claimed as live work")
    _ = agent.apply(["hook_event_name": "Interrupt"], at: origin)
    check(agent.phase == .interrupted, "Interrupted turn is not marked complete")
    let isolated = FileManager.default.temporaryDirectory.appendingPathComponent("Damla-agent-test-\(UUID().uuidString)")
    do {
        defer { try? FileManager.default.removeItem(at: isolated) }
        let event: [String: Any] = ["session_id": "../../unsafe-session", "hook_event_name": "UserPromptSubmit", "cwd": "/Users/example/Project", "prompt": "PRIVATE PROMPT", "transcript_path": "/secret/transcript"]
        let input = try JSONSerialization.data(withJSONObject: event)
        try AgentEventStore.receive(provider: .claude, input: input, directory: isolated, now: Date())
        let records = AgentEventStore.read(directory: isolated)
        check(records.count == 1 && records[0].project == "Project", "Hook event round-trips in isolated store")
        let encoded = try JSONEncoder().encode(records)
        let text = String(decoding: encoded, as: UTF8.self)
        check(!text.contains("PRIVATE PROMPT") && !text.contains("/secret") && !text.contains("/Users/example"), "Status storage excludes prompt, transcript and full path")
        check(!records[0].id.contains("..") && !records[0].id.contains("/"), "Untrusted session id cannot escape store")
        try AgentEventStore.receive(provider: .codex, input: input, directory: isolated)
        check(AgentEventStore.read(directory: isolated).count == 2, "Providers with same session id cannot overwrite one another")
        let missing: [String: Any] = ["hook_event_name": "Stop"]
        try AgentEventStore.receive(provider: .codex, input: JSONSerialization.data(withJSONObject: missing), directory: isolated)
        check(AgentEventStore.read(directory: isolated).count == 2, "Malformed event cannot create phantom session")
    } catch { failures.append("Agent fixture: \(error)") }
    print("Damla self-test: \(count - failures.count)/\(count) passed")
    for failure in failures { print("FAIL: \(failure)") }
    return failures.isEmpty ? 0 : 1
}
