import Foundation

func runSelfTests() -> Int32 {
    var failures: [String] = []
    var count = 0
    func check(_ condition: @autoclosure () -> Bool, _ name: String) {
        count += 1
        if !condition() { failures.append(name) }
    }
    let origin = Date(timeIntervalSince1970: 1_000_000)
    var focus = FocusSession()
    focus.start(at: origin)
    check(focus.remaining(at: origin.addingTimeInterval(60)) == 1440, "Timer tracks elapsed time")
    focus.pause(at: origin.addingTimeInterval(60))
    check(focus.remaining(at: origin.addingTimeInterval(600)) == 1440, "Paused timer does not drift")
    focus.start(at: origin.addingTimeInterval(600))
    check(focus.remaining(at: origin.addingTimeInterval(660)) == 1380, "Resume keeps remaining time")
    let saved = try! JSONEncoder().encode(focus)
    var restored = try! JSONDecoder().decode(FocusSession.self, from: saved)
    check(restored.remaining(at: origin.addingTimeInterval(720)) == 1320, "Restored timer follows wall clock")
    check(restored.finishIfNeeded(at: origin.addingTimeInterval(3000)), "Overdue session completes after wake")
    check(!restored.finishIfNeeded(at: origin.addingTimeInterval(3001)), "Completion counted only once")
    check(restored.remaining(at: origin.addingTimeInterval(3001)) == 0, "Remaining never negative")
    focus.reset(minutes: 5, phase: .rest)
    check(focus.duration == 300 && !focus.running && focus.phase == .rest, "Break resets state")
    check(!ClipRules.shouldCapture(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]), "Password marker excluded")
    check(!ClipRules.shouldCapture(types: ["org.nspasteboard.TransientType"]), "Transient data excluded")
    check(!ClipRules.shouldCapture(types: ["org.nspasteboard.AutoGeneratedType"]), "Own copies excluded")
    check(ClipRules.shouldCapture(types: ["public.png"]), "Images accepted")
    var entries = (0..<70).map { ClipEntry(kind: .text, text: "Test \($0)", date: origin.addingTimeInterval(Double($0))) }
    entries[0].pinned = true
    let trimmed = ClipRules.trimmed(entries)
    check(trimmed.count == 60, "Clipboard bounded to 60")
    check(trimmed.first?.pinned == true, "Pinned entry retained ahead of recents")
    let images = (0..<8).map { _ in ClipEntry(kind: .image, imageData: Data(count: 4 * 1024 * 1024)) }
    check(ClipRules.trimmed(images).reduce(0) { $0 + $1.byteSize } <= 24 * 1024 * 1024, "Clipboard disk budget bounded")
    let temp = FileManager.default.temporaryDirectory.appendingPathComponent("Damla-test-\(UUID().uuidString)")
    do {
        try FileManager.default.createDirectory(at: temp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: temp) }
        let file = temp.appendingPathComponent("original.txt")
        try Data("original stays".utf8).write(to: file)
        let ref = ShelfItem(url: file)
        let roundtrip = try JSONDecoder().decode(ShelfItem.self, from: JSONEncoder().encode(ref))
        check(roundtrip.url.standardizedFileURL.path == file.standardizedFileURL.path, "Shelf reference survives save/reload")
        let original = try String(contentsOf: file, encoding: .utf8)
        check(original == "original stays", "Shelf leaves source unchanged")
    } catch { failures.append("Shelf fixture: \(error)") }
    let notch = Layout.Metrics(notchWidth: 185, notchHeight: 32, hasNotch: true)
    let flat = Layout.Metrics(notchWidth: 0, notchHeight: 30, hasNotch: false)
    check(Layout.shapeSize(.closed, notch, compactContent: false).width == 185 + 12, "Idle notch hugs the physical notch")
    check(Layout.shapeSize(.hud, notch, compactContent: false).width > Layout.shapeSize(.closed, notch, compactContent: true).width, "HUD widens beyond compact content")
    check(Layout.shapeSize(.expanded, notch, compactContent: false).height == 32 + Layout.contentHeight, "Expanded panel sits under the notch")
    check(Layout.shapeSize(.expanded, flat, compactContent: false).height == 12 + Layout.contentHeight, "Notchless panel uses a slim header")
    let window = Layout.windowSize(notch)
    let visible = Layout.visibleRect(.expanded, notch, compactContent: true, midX: 0, top: 0)
    check(window.width >= visible.width && window.height >= visible.height, "Window always contains the drawn shape")
    print("Damla self-test: \(count - failures.count)/\(count) passed")
    for failure in failures { print("FAIL: \(failure)") }
    return failures.isEmpty ? 0 : 1
}
