import AppKit
import Foundation
import PDFKit
import CoreAudio
import ApplicationServices

func runSelfTests() -> Int32 {
    var failures: [String] = []
    var count = 0
    func check(_ condition: @autoclosure () -> Bool, _ name: String) {
        count += 1
        if !condition() { failures.append(name) }
    }
    let origin = Date(timeIntervalSince1970: 1_000_000)
    var focus = FocusSession()
    focus.start(at: origin)
    check(focus.remaining(at: origin.addingTimeInterval(60)) == 1440, "Timer tracks elapsed time")
    focus.pause(at: origin.addingTimeInterval(60))
    check(focus.remaining(at: origin.addingTimeInterval(600)) == 1440, "Paused timer does not drift")
    focus.start(at: origin.addingTimeInterval(600))
    check(focus.remaining(at: origin.addingTimeInterval(660)) == 1380, "Resume keeps remaining time")
    let saved = try! JSONEncoder().encode(focus)
    var restored = try! JSONDecoder().decode(FocusSession.self, from: saved)
    check(restored.remaining(at: origin.addingTimeInterval(720)) == 1320, "Restored timer follows wall clock")
    check(restored.finishIfNeeded(at: origin.addingTimeInterval(3000)), "Overdue session completes after wake")
    check(!restored.finishIfNeeded(at: origin.addingTimeInterval(3001)), "Completion counted only once")
    check(restored.remaining(at: origin.addingTimeInterval(3001)) == 0, "Remaining never negative")
    focus.reset(minutes: 5, phase: .rest)
    check(focus.duration == 300 && !focus.running && focus.phase == .rest, "Break resets state")
    check(!ClipRules.shouldCapture(types: ["public.utf8-plain-text", "org.nspasteboard.ConcealedType"]), "Password marker excluded")
    check(!ClipRules.shouldCapture(types: ["org.nspasteboard.TransientType"]), "Transient data excluded")
    check(!ClipRules.shouldCapture(types: ["org.nspasteboard.AutoGeneratedType"]), "Own copies excluded")
    check(ClipRules.shouldCapture(types: ["public.png"]), "Images accepted")
    var entries = (0..<70).map { ClipEntry(kind: .text, text: "Test \($0)", date: origin.addingTimeInterval(Double($0))) }
    entries[0].pinned = true
    let trimmed = ClipRules.trimmed(entries)
    check(trimmed.count == 60, "Clipboard bounded to 60")
    check(trimmed.first?.pinned == true, "Pinned entry retained ahead of recents")
    let images = (0..<8).map { _ in ClipEntry(kind: .image, imageData: Data(count: 4 * 1024 * 1024)) }
    check(ClipRules.trimmed(images).reduce(0) { $0 + $1.byteSize } <= 24 * 1024 * 1024, "Clipboard disk budget bounded")
    let temp = FileManager.default.temporaryDirectory.appendingPathComponent("Damla-test-\(UUID().uuidString)")
    do {
        try FileManager.default.createDirectory(at: temp, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: temp) }
        let file = temp.appendingPathComponent("original.txt")
        try Data("original stays".utf8).write(to: file)
        let ref = ShelfItem(url: file)
        let roundtrip = try JSONDecoder().decode(ShelfItem.self, from: JSONEncoder().encode(ref))
        check(roundtrip.url.standardizedFileURL.path == file.standardizedFileURL.path, "Shelf reference survives save/reload")
        let original = try String(contentsOf: file, encoding: .utf8)
        check(original == "original stays", "Shelf leaves source unchanged")
    } catch { failures.append("Shelf fixture: \(error)") }
    let notch = Layout.Metrics(notchWidth: 185, notchHeight: 32, hasNotch: true)
    let flat = Layout.Metrics(notchWidth: 0, notchHeight: 30, hasNotch: false)
    check(Layout.shapeSize(.closed, notch, compactSlots: 0).width == 185 + 12, "Idle notch hugs the physical notch")
    check(Layout.shapeSize(.hud, notch, compactSlots: 0).width > Layout.shapeSize(.closed, notch, compactSlots: 2).width, "HUD widens beyond compact content")
    check(Layout.shapeSize(.closed, notch, compactSlots: 2).width > Layout.shapeSize(.closed, notch, compactSlots: 1).width, "Two activities widen the closed notch")
    check(Layout.shapeSize(.expanded, notch, compactSlots: 0).height == 32 + Layout.contentHeight, "Expanded panel sits under the notch")
    check(Layout.shapeSize(.expanded, flat, compactSlots: 0).height == 12 + Layout.contentHeight, "Notchless panel uses a slim header")
    check(Layout.shapeSize(.expanded, notch, compactSlots: 0, content: Layout.tallContentHeight).height == 32 + Layout.tallContentHeight
          && Layout.windowSize(notch).height >= 32 + Layout.tallContentHeight + Layout.pillGap + Layout.pillHeight, "Lyrics panel grows down inside the window")
    let window = Layout.windowSize(notch)
    let visible = Layout.visibleRect(.expanded, notch, compactSlots: 2, midX: 0, top: 0)
    check(window.width >= visible.width && window.height >= visible.height, "Window always contains the drawn shape")
    // Regression: the fixed-size host remains over the browser after collapse; only the visible rect may receive clicks.
    for metrics in [notch, flat] {
        let closed = Layout.visibleRect(.closed, metrics, compactSlots: 2, midX: -700, top: 900)
        let expanded = Layout.visibleRect(.expanded, metrics, compactSlots: 2, midX: -700, top: 900)
        let browserToolbar = CGPoint(x: -700, y: closed.minY - 1)
        check(expanded.contains(browserToolbar) && !closed.contains(browserToolbar), "Collapse releases browser toolbar on either display style")
        check(closed.contains(CGPoint(x: closed.minX + 10, y: closed.midY)), "Closed activity stays clickable on offset displays")
        check(!expanded.contains(CGPoint(x: expanded.maxX + 1, y: expanded.midY)), "Transparent shadow margin stays outside input area")
        let hud = Layout.visibleRect(.hud, metrics, compactSlots: 0, midX: -700, top: 900)
        let drop = Layout.visibleRect(.drop, metrics, compactSlots: 0, midX: -700, top: 900)
        let basketPoint = CGPoint(x: -700, y: hud.minY - Layout.dropBandHeight / 2)
        check(drop.contains(basketPoint) && !hud.contains(basketPoint) && !closed.contains(basketPoint), "Drop target is interactive only while its basket is visible")
        check(expanded.contains(CGPoint(x: -700, y: expanded.minY + Layout.pillHeight / 2)), "Expanded tab pill remains interactive")
    }
    var cleaning = CleaningSession()
    cleaning.start(at: 100)
    check(cleaning.remaining(at: 159) == 1 && !cleaning.shouldUnlock(at: 159), "Cleaning lock lasts at most 60 seconds")
    check(cleaning.shouldUnlock(at: 160), "Cleaning lock expires without a keyboard event")
    cleaning.start(at: 100, duration: 999)
    check(cleaning.shouldUnlock(at: 160), "Cleaning cannot exceed hard timeout")
    cleaning.escape(down: true, at: 110)
    cleaning.escape(down: true, at: 111.5)
    check(!cleaning.shouldUnlock(at: 111.9) && cleaning.shouldUnlock(at: 112), "Held Esc unlocks after two seconds; repeat does not reset it")
    cleaning.escape(down: false, at: 111)
    check(!cleaning.shouldUnlock(at: 112), "Brief Esc press does not accidentally unlock")
    cleaning.stop()
    check(cleaning.shouldUnlock(at: 101) && cleaning.remaining(at: 101) == 0, "Stopping cleaning clears every deadline")

    var agent = AgentSession(id: "test", provider: .codex, project: "Damla", updated: origin)
    _ = agent.apply(["hook_event_name": "UserPromptSubmit"], at: origin)
    check(agent.phase == .working, "Agent begins from prompt event")
    check(agent.turnStarted == origin && agent.toolCalls == 0, "Prompt starts the turn clock and counter")
    _ = agent.apply(["hook_event_name": "PreToolUse", "tool_use_id": "zero", "tool_name": "Read"], at: origin)
    check(agent.tool == "Read", "Running tool is remembered while it runs")
    _ = agent.apply(["hook_event_name": "PostToolUse", "tool_use_id": "zero", "tool_name": "Read"], at: origin)
    check(agent.tool == nil && agent.toolCalls == 1, "Completed tool clears the running tool and counts")
    _ = agent.apply(["hook_event_name": "PermissionRequest", "tool_use_id": "one", "tool_name": "Bash"], at: origin)
    check(agent.waitingTool == "Bash" && agent.waitingSince == origin, "Approval records the tool and when waiting began")
    _ = agent.apply(["hook_event_name": "PreToolUse", "tool_use_id": "two", "tool_name": "Bash"], at: origin)
    _ = agent.apply(["hook_event_name": "PostToolUse", "tool_use_id": "two", "tool_name": "Bash"], at: origin)
    check(agent.phase == .waiting && agent.pending.contains("one"), "Parallel tool does not erase outstanding approval")
    _ = agent.apply(["hook_event_name": "PostToolUse", "tool_use_id": "one", "tool_name": "Bash"], at: origin)
    check(agent.phase == .working && agent.pending.isEmpty && agent.waitingSince == nil, "Matching tool completion clears approval")
    _ = agent.apply(["hook_event_name": "PermissionRequest", "tool_use_id": "three", "tool_name": "Edit"], at: origin)
    _ = agent.apply(["hook_event_name": "PermissionDenied", "tool_use_id": "three", "tool_name": "Edit"], at: origin)
    check(agent.phase == .working && agent.waitingTool == nil, "Denied approval returns to working")
    _ = agent.apply(["hook_event_name": "PreToolUse", "tool_use_id": "four", "tool_name": "request_permissions"], at: origin)
    check(agent.phase == .waiting && agent.detail == "Onay bekliyor", "Codex app's permission request shows as waiting for approval")
    _ = agent.apply(["hook_event_name": "PostToolUse", "tool_use_id": "four", "tool_name": "request_permissions"], at: origin)
    check(agent.phase == .working && agent.pending.isEmpty, "Answering it in Codex returns to working")
    check(AgentSession.toolLabel("Bash") == "Komut çalıştırıyor" && AgentSession.toolLabel("mcp__figma__get_design") == "design kullanıyor", "Tool labels read naturally")
    check(!agent.apply(["hook_event_name": "Notification", "notification_type": "idle_prompt"], at: origin), "Claude idle nudge is not shown as approval")
    _ = agent.apply(["hook_event_name": "Stop"], at: origin)
    check(agent.phase == .done && agent.turnStarted != nil && (agent.toolCalls ?? 0) >= 3, "Stop keeps the turn's duration and count for the summary")
    check(AgentText.activity(agent, at: origin).text.contains("çağrı"), "Finished row still shows the call count")
    check(!agent.visibleInNotch(at: origin.addingTimeInterval(61)), "Completed badge expires")
    _ = agent.apply(["hook_event_name": "UserPromptSubmit"], at: origin)
    check(agent.effectivePhase(at: origin.addingTimeInterval(1801)) == .stale, "Missing hook heartbeat is not claimed as live work")
    _ = agent.apply(["hook_event_name": "Interrupt"], at: origin)
    check(agent.phase == .interrupted, "Interrupted turn is not marked complete")
    let isolated = FileManager.default.temporaryDirectory.appendingPathComponent("Damla-agent-test-\(UUID().uuidString)")
    do {
        defer { try? FileManager.default.removeItem(at: isolated) }
        let event: [String: Any] = ["session_id": "../../unsafe-session", "hook_event_name": "UserPromptSubmit", "cwd": "/Users/example/Project", "prompt": "PRIVATE PROMPT", "transcript_path": "/secret/transcript"]
        let input = try JSONSerialization.data(withJSONObject: event)
        try AgentEventStore.receive(provider: .claude, input: input, directory: isolated, now: Date(), host: "com.apple.Terminal")
        let records = AgentEventStore.read(directory: isolated)
        check(records.count == 1 && records[0].project == "Project", "Hook event round-trips in isolated store")
        check(records[0].host == "com.apple.Terminal", "Host app is stored with the session")
        let stopEvent = try JSONSerialization.data(withJSONObject: ["session_id": "../../unsafe-session", "hook_event_name": "Stop"])
        try AgentEventStore.receive(provider: .claude, input: stopEvent, directory: isolated)
        try AgentEventStore.receive(provider: .claude, input: stopEvent, directory: isolated)
        check(AgentEventStore.todayTurns(directory: isolated) == 2, "Completed turns are counted per day")
        check(AgentEventStore.todayTurns(directory: isolated, now: Date().addingTimeInterval(2 * 24 * 3600)) == 0, "Turn counter resets on a new day")
        let encoded = try JSONEncoder().encode(records)
        let text = String(decoding: encoded, as: UTF8.self)
        check(!text.contains("PRIVATE PROMPT") && !text.contains("/secret") && !text.contains("/Users/example"), "Status storage excludes prompt, transcript and full path")
        check(!records[0].id.contains("..") && !records[0].id.contains("/"), "Untrusted session id cannot escape store")
        try AgentEventStore.receive(provider: .codex, input: input, directory: isolated)
        check(AgentEventStore.read(directory: isolated).count == 2, "Providers with same session id cannot overwrite one another")
        let missing: [String: Any] = ["hook_event_name": "Stop"]
        try AgentEventStore.receive(provider: .codex, input: JSONSerialization.data(withJSONObject: missing), directory: isolated)
        check(AgentEventStore.read(directory: isolated).count == 2, "Malformed event cannot create phantom session")
        let status: [String: Any] = ["session_id": "../../unsafe-session", "model": ["display_name": "Opus"],
                                     "context_window": ["used_percentage": 61.6],
                                     "rate_limits": ["five_hour": ["used_percentage": 23.5, "resets_at": Date().timeIntervalSince1970 + 3600],
                                                     "seven_day": ["used_percentage": 41.2, "resets_at": Date().timeIntervalSince1970 - 10]]]
        let line = AgentEventStore.receiveStatus(provider: .claude, input: try JSONSerialization.data(withJSONObject: status), directory: isolated)
        let withContext = AgentEventStore.read(directory: isolated).first { $0.id == records[0].id }
        check(line == "Opus · bağlam %62 · 5 sa %24" && withContext?.context == 62 && withContext?.model == "Opus", "Status line records context and prints a short line")
        let usage = AgentEventStore.readUsage(directory: isolated)
        check(usage?.fiveHour?.percent == 23.5 && usage?.sevenDay == nil, "Rate limits are kept until their window resets")
        check(AgentEventStore.read(directory: isolated).count == 2, "Usage file is not mistaken for a session")
        _ = AgentEventStore.receiveStatus(provider: .claude, input: try JSONSerialization.data(withJSONObject: ["session_id": "unknown"]), directory: isolated)
        check(AgentEventStore.read(directory: isolated).count == 2, "Status line never creates a session by itself")
        let watcher = AgentStatusService()
        var warnings: [Int] = []
        watcher.onUsageWarning = { percent, _ in warnings.append(percent) }
        let reset = Date().addingTimeInterval(3600)
        func limits(_ percent: Double) -> AgentUsage? { AgentUsage(["five_hour": ["used_percentage": percent, "resets_at": reset.timeIntervalSince1970]], now: Date()) }
        for percent in [50.0, 81, 85, 96, 97] { watcher.checkUsage(limits(percent)) }
        check(warnings == [81, 96], "Five-hour use warns once at 80 % and once at 95 %")
        AgentEventStore.remove(id: records[0].id, directory: isolated)
        check(AgentEventStore.read(directory: isolated).count == 1, "Removed session leaves the store")
    } catch { failures.append("Agent fixture: \(error)") }
    check(AudioOutput.icon(name: "Erkam’s AirPods Pro", transport: kAudioDeviceTransportTypeBluetooth) == "airpods.pro"
          && AudioOutput.icon(name: "MacBook Pro Speakers", transport: kAudioDeviceTransportTypeBuiltIn) == "laptopcomputer"
          && AudioOutput.icon(name: "DELL U2723QE", transport: kAudioDeviceTransportTypeDisplayPort) == "display", "Output icons follow the device")
    check(AudioOutput.shortName("Erkam’ın AirPods Pro", transport: kAudioDeviceTransportTypeBluetooth) == "AirPods Pro"
          && AudioOutput.shortName("MacBook Pro Hoparlörü", transport: kAudioDeviceTransportTypeBuiltIn) == "Hoparlör", "Output names fit the capsule")
    var gesture = PanelSwipeGesture()
    check(gesture.feed(up: 0, right: -30, precise: false, began: false, ended: false, momentum: false) == .pass, "Mouse wheels scroll the page, never swipe")
    _ = gesture.feed(up: 0, right: 0, precise: true, began: true, ended: false, momentum: false, time: 0)
    let scroll = (1...8).map { gesture.feed(up: 10, right: -8, precise: true, began: false, ended: false, momentum: false, time: Double($0) * 0.016) }
    check(scroll.allSatisfy { $0 == .pass }, "A vertical start stays a scroll even if it drifts sideways")
    _ = gesture.feed(up: 0, right: 0, precise: true, began: false, ended: true, momentum: false, time: 0.2)
    // A slow drag: the page follows, and past 70 pt it turns on release.
    _ = gesture.feed(up: 0, right: 0, precise: true, began: true, ended: false, momentum: false, time: 1)
    let drag = (1...8).map { gesture.feed(up: 0, right: -10, precise: true, began: false, ended: false, momentum: false, time: 1 + Double($0) * 0.05) }
    check(drag.last == PanelSwipeGesture.Result(consume: true, event: .drag(-80)), "The page follows the fingers")
    check(gesture.feed(up: 0, right: 0, precise: true, began: false, ended: true, momentum: false, time: 1.5).event == .release(.next), "Far enough turns to the next page")
    // A short pull that stops: springs back.
    _ = gesture.feed(up: 0, right: 0, precise: true, began: true, ended: false, momentum: false, time: 2)
    _ = (1...4).map { gesture.feed(up: 0, right: 8, precise: true, began: false, ended: false, momentum: false, time: 2 + Double($0) * 0.05) }
    check(gesture.feed(up: 0, right: 0, precise: true, began: false, ended: true, momentum: false, time: 2.6).event == .release(nil), "A short pull springs back")
    check(PanelSwipeGesture.decision(travel: 25, velocity: 900) == .previous && PanelSwipeGesture.decision(travel: 25, velocity: -900) == nil,
          "A quick flick turns the page, against its own travel it does not")
    check(abs(PanelSwipeGesture.rubberBand(-400)) < 44 && PanelSwipeGesture.rubberBand(-400) < 0 && PanelSwipeGesture.rubberBand(10) < 10,
          "With no page there the swipe only gives a little")
    check(gesture.feed(up: 0, right: -40, precise: true, began: false, ended: false, momentum: true) == .pass, "Momentum never turns a page")
    let profile = #"{"SPBluetoothDataType":[{"device_connected":[{"Erkam’ın AirPods Pro":{"device_batteryLevelLeft":"80%","device_batteryLevelRight":"75 %","device_batteryLevelCase":"60%"}},{"MX Keys Mini":{"device_minorType":"Keyboard"}}],"device_not_connected":[{"iPhone":{}}]}]}"#
    let buds = BluetoothBattery.parse(Data(profile.utf8), name: "Erkam’ın AirPods Pro")
    check(buds?.summary == "S %80 · Sa %75 · K %60", "AirPods battery reads each bud and the case")
    check(BluetoothBattery.parse(Data(profile.utf8), name: "iPhone") == nil && BluetoothBattery.parse(Data(profile.utf8), name: "MX Keys Mini") == nil,
          "No battery line for disconnected or battery-less devices")
    check(BluetoothBattery.parseAll(Data(profile.utf8)).keys.sorted() == ["Erkam’ın AirPods Pro"], "Outputs list reads every connected battery at once")
    check(DevServer.isDevProcess(path: "/opt/homebrew/bin/node", cwd: "/Users/x/site")
          && !DevServer.isDevProcess(path: "/Applications/Docker.app/Contents/MacOS/com.docker.backend", cwd: "/Users/x")
          && !DevServer.isDevProcess(path: "/usr/libexec/rapportd", cwd: "/Users/x")
          && !DevServer.isDevProcess(path: "/opt/homebrew/bin/mongod", cwd: "/"), "Only shell-started processes count as dev servers")
    check(DevServer.projectName(cwd: "/Users/x/Projects/shop/.data/postgres", fileExists: { $0 == "/Users/x/Projects/shop/.git" }) == "shop"
          && DevServer.projectName(cwd: "/Users/x/tmp/api", fileExists: { _ in false }) == "api", "A server is named after its repository")
    check(DevServer(pid: 1, port: 5432, name: "postgres", project: "shop").isDatabase
          && !DevServer(pid: 1, port: 3000, name: "node", project: "shop").isDatabase, "Databases are told apart from web servers")
    check(CalendarService.joinURL(in: [nil, "Oda 3", "Katıl: https://us02web.zoom.us/j/8123456789?pwd=abc ve not"])?.absoluteString == "https://us02web.zoom.us/j/8123456789?pwd=abc"
          && CalendarService.joinURL(in: ["https://meet.google.com/abc-defg-hij"])?.host == "meet.google.com"
          && CalendarService.joinURL(in: ["https://teams.microsoft.com/l/meetup-join/19%3ameeting_x"]) != nil
          && CalendarService.joinURL(in: ["https://example.com/j/1", "Toplantı odası"]) == nil, "Video-call links are found, other links are not")
    let clock = Date()
    let meetings = [CalendarService.Meeting(id: "old", title: "Eski", start: clock.addingTimeInterval(-900), end: clock.addingTimeInterval(900), joinURL: nil),
                    CalendarService.Meeting(id: "day", title: "Tatil", start: clock.addingTimeInterval(-3600), end: clock.addingTimeInterval(20000), joinURL: nil),
                    CalendarService.Meeting(id: "late", title: "Sonra", start: clock.addingTimeInterval(7200), end: clock.addingTimeInterval(9000), joinURL: nil),
                    CalendarService.Meeting(id: "next", title: "Standup", start: clock.addingTimeInterval(240), end: clock.addingTimeInterval(1200), joinURL: nil)]
    let picked = CalendarService.pick(meetings, allDay: ["day"], now: clock)
    check(picked?.id == "next", "Next meeting skips all-day events and ones running for over five minutes")
    check(picked.map { CalendarService.countdown($0, at: clock) } == "4 dk" && picked.map { CalendarService().isSoon($0, at: clock) } == true
          && picked.map { CalendarService().isSoon($0, at: clock.addingTimeInterval(-700)) } == false, "The countdown starts ten minutes before")
    let tabDefaults = UserDefaults(suiteName: "Damla-tabs-\(UUID().uuidString)")!
    tabDefaults.set(["Özet", "Odak"], forKey: "enabledTabs")
    let upgraded = PanelTab.loadEnabled(defaults: tabDefaults)
    tabDefaults.set(PanelTab.allCases.map(\.rawValue), forKey: "knownTabs")
    check(upgraded == [.home, .focus, .mirror, .shortcuts] && PanelTab.loadEnabled(defaults: tabDefaults) == [.home, .focus],
          "A page added in an update starts on; one the user turned off stays off")
    let shelfFolder = FileManager.default.temporaryDirectory.appendingPathComponent("Damla-shelf-\(UUID().uuidString)")
    try? FileManager.default.createDirectory(at: shelfFolder, withIntermediateDirectories: true)
    let png = shelfFolder.appendingPathComponent("foto.png")
    let bitmap = NSBitmapImageRep(bitmapDataPlanes: nil, pixelsWide: 200, pixelsHigh: 100, bitsPerSample: 8, samplesPerPixel: 4, hasAlpha: true,
                                  isPlanar: false, colorSpaceName: .deviceRGB, bytesPerRow: 0, bitsPerPixel: 0)
    try? bitmap?.representation(using: .png, properties: [:])?.write(to: png)
    let jpeg = ShelfAction.writeImage(png, as: .jpeg, suffix: nil, scale: 1, quality: 0.9)
    let half = ShelfAction.writeImage(png, as: .png, suffix: "küçük", scale: 0.5, quality: 0.9)
    let halfWidth = half.flatMap { NSImageRep(contentsOf: $0)?.pixelsWide }
    check(jpeg?.lastPathComponent == "foto.jpeg" && half?.lastPathComponent == "foto-küçük.png" && halfWidth == 100
          && FileManager.default.fileExists(atPath: png.path), "Image conversions write new files beside the original")
    check(ShelfAction.destination(for: png, suffix: nil, ext: "jpeg")?.lastPathComponent == "foto 2.jpeg", "Conversions never overwrite a file")
    check(ShelfAction.available(for: png, shelf: [png]).contains(.convert(.jpeg)) && !ShelfAction.available(for: png, shelf: [png]).contains(.convert(.png)),
          "Images are offered the other formats")
    let pdfs = (1...2).map { shelfFolder.appendingPathComponent("belge\($0).pdf") }
    for pdf in pdfs {
        let document = PDFDocument()
        if let image = NSImage(contentsOf: png), let page = PDFPage(image: image) { document.insert(page, at: 0) }
        document.write(to: pdf)
    }
    let merged = ShelfAction.merge(pdfs, near: pdfs[0])
    check(merged.flatMap { PDFDocument(url: $0)?.pageCount } == 2 && ShelfAction.available(for: pdfs[0], shelf: pdfs) == [.mergePDFs]
          && ShelfAction.available(for: pdfs[0], shelf: [pdfs[0]]).isEmpty, "PDFs on the shelf merge into one")
    try? FileManager.default.removeItem(at: shelfFolder)
    var focusClock = FocusSession()
    focusClock.reset(minutes: 37)
    check(focusClock.duration == 37 * 60 && focusClock.remaining() == 37 * 60, "Any focus length can be set")
    let axSelf = AXUIElementCreateApplication(getpid())
    func statusItem(_ x: CGFloat) -> MenuBarItems.Item {
        MenuBarItems.Item(title: "\(Int(x))", frame: CGRect(x: x, y: 458, width: 24, height: 33), element: axSelf, app: .current)
    }
    let notchRect = CGRect(x: 3223, y: 458, width: 185, height: 32), barRect = CGRect(x: 2560, y: 458, width: 1512, height: 32)
    let hiddenNow = MenuBarOverflow.hidden([statusItem(3300), statusItem(3536), statusItem(3700), statusItem(1200)], notch: notchRect, bar: barRect,
                                           menus: [CGRect(x: 3495, y: 458, width: 50, height: 33)])
    check(hiddenNow.map(\.title) == ["3300", "3536"], "Behind the notch or under the app's menus is hidden; clear space and other screens are not")
    var lowBattery: [String] = []
    let watcher = DeviceBatteryWatcher()
    watcher.onLow = { name, _, level in lowBattery.append("\(name) \(level)") }
    let mouse = { (level: Int) in ["Magic Mouse": BluetoothBattery.Levels(left: nil, right: nil, case: nil, main: level, kind: "Mouse")] }
    for level in [40, 9, 8, 4, 3, 60, 7] { watcher.evaluate(mouse(level)) }
    check(lowBattery == ["Magic Mouse 9", "Magic Mouse 4", "Magic Mouse 7"], "Low battery warns at 10 % and 5 %, again only after charging")
    check(DeviceBatteryWatcher.icon(for: mouse(5)["Magic Mouse"]!, name: "Magic Mouse") == "magicmouse", "Low battery shows the device's own icon")
    check(buds?.lowest == 60 && BluetoothBattery.Levels(left: nil, right: nil, case: nil, main: 15).lowest == 15, "Lowest level drives the low-battery tint")
    runMediaSelfTests { condition, name in check(condition, name) }
    runApprovalSelfTests { condition, name in check(condition, name) }
    runLyricsSelfTests { condition, name in check(condition, name) }
    runHookInstallerSelfTests { condition, name in check(condition, name) }
    print("Damla self-test: \(count - failures.count)/\(count) passed")
    for failure in failures { print("FAIL: \(failure)") }
    return failures.isEmpty ? 0 : 1
}
